### ISSUE TITLE
Teaweb-agent包里默认没有scripts目录及启动脚本

### ISSUE THREAD

**Issue by flowerpig2012** [TeaWeb/agent#1]
Teaweb-agent包里默认没有scripts目录及启动脚本

启动脚本在Teaweb主包里，agent包里反而没有。
安装安装文档，还需要去另一个包里去找到，scp到web real机器上。弄自启动。

希望将scripts下的teaweb-agent文件放在agent包中。省的还需要去scp一下。比较agent支持自动升级。一次性设置好以后就不需要管了。

**Comment by iwind** [comment]
v0.1.6解决了这个问题，增加了script，并增加了 bin/service-install  和 bin/service-uninstall 两个命令。

另外，agent是支持自动升级的。
